### ISSUE TITLE
Allow the user to show timestamps of the image instead of the time recorded

### ISSUE THREAD

**Issue by ACH1980** [vannizhang/wayback#65]
As stated above there should be an option for the user to select image sources from the time the image was taken, not when it was saved to WIW Database.

For example, so you could have in this list written 2012 instead of 2016...
![image](https://user-images.githubusercontent.com/39656381/177806274-18190242-b65e-4a44-8425-75d6af29b6c4.png)

**Comment by vannizhang** [comment]
Hi @ACH1980 ,

I reached out the project manager @robert-waterman of the Wayback App regarding this issue and here is his reply:

> World Imagery is composed of hundreds of thousands of individual images stitched together to form a single basemap layer. Esri does not have access to all of the individual images used to produce the basemap. Therefore, we do not have a practical way of creating an archive by acquisition date (which is a property of each individual image). As such, we provide an archive consisting of versions of the World Imagery layer arranged by release date (a property of each layer).

Hope it's helpful. Thanks.
