### ISSUE TITLE
World Imagery Wayback should provide a notification indicating if a user has a lack of privileges to create a map, rather than looping the user through the dialog.

### ISSUE THREAD

**Issue by chrislandvogt** [vannizhang/wayback#75]
If the user is logged in with reduced user type privileges (eg. Mobile Worker/Editor), the create map dialog will loop and not create a map, rather than let the user know that they don't have the required permissions. The user experience could be enhanced if a warning/error was provided to the user.

Devtools shows the following in the network traffic response  {"error":{"code":403,"messageCode":"GWM_0003","message":"You do not have permissions to access this resource or perform this operation.","details":[]}}

Which is a good indicator if you use dev tools, but few users do.

**Comment by vannizhang** [comment]
@chrislandvogt Thanks for opening this issue. I agree with you that the app should show a warning message if the signed in user has no permission to create content in the portal. I will let you know when this feature get implemented in the app.

**Comment by vannizhang** [comment]
Made a UX improvement to the "Save as Webmap Modal", it will show a warning message if the signed-in user has no privilege to create content in their ArcGIS Online organization. It also provide the user a link below so they can sign in using a different account:

![image](https://user-images.githubusercontent.com/3142684/209881413-241b39c2-a743-4ed5-858e-027d8719f21a.png)

@chrislandvogt

**Comment by chrislandvogt** [comment]
@vannizhang - thank you so much.
