### ISSUE TITLE
Download Tile Package: Add ability to cancel/remove an in progress job from my export queue

### ISSUE THREAD

**Issue by robert-waterman** [vannizhang/wayback#91]
A user currently cannot cancel/remove a job from their queue. 
![image](https://github.com/vannizhang/wayback/assets/40008490/2c84db09-cee9-480e-bcbf-cd8d1f372284)

There may be cases when they want to abandon a job and start over.

**Comment by vannizhang** [comment]
@robert-waterman ready for testing on DEV.

**Comment by robert-waterman** [comment]
Verified fixed.
